[tool.poetry]
name = "oop-1"
version = "0"
description = "VK"
authors = ["ViktorKozh <viktor.ru253@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
